info:
  title: openAPi specification for project
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000/

tags:
  - name: Trackers
    description: crud on trackers
  - name: logs
    description: crud on logs

paths:
  /Trackers:
    summary: Tacker read create
    get:
      tags:
        - Trackers
      responses:
        200:
          description: Success
        400:
          description: incorrect input
    post:
      tags:
        - Trackers
      responses:
        200:
          description: Success
        400:
          description: incorrect input

  /Tracker_manipulate:
    summary: Tacker update & delete
    put:
      tags:
        - Trackers
      responses:
        200:
          description: Success
        400:
          description: incorrect input
    delete:
      tags:
        - Trackers
      responses:
        200:
          description: Success
        400:
          description: incorrect input
  /Tracker_logs:
    summary: read create
    get:
      tags:
        - logs
      responses:
        200:
          description: Success
        400:
          description: incorrect input
    post:
      tags:
        - logs
      responses:
        200:
          description: Success
        400:
          description: incorrect input
  /log_manipulate:
    summary: log update & delete
    put:
      tags:
        - logs
      responses:
        200:
          description: Success
        400:
          description: incorrect input
    delete:
      tags:
        - logs
      responses:
        200:
          description: Success
        400:
          description: incorrect input
